export const TAK_KNOWLEDGE = [
  'Project knowledge (curated from the TAK whitepaper):',
  'Origin: TAK began in a small café in Farahan, Iran. A group of friends noticed the wholesale price of coffee is far below what any single café or person pays. They decided to pool their money and buy coffee together, giving it to Alireza, the café owner, to serve at a discount to everyone who contributed. Each contributor gets coupons proportional to what they put in.',
  'What TAK is: TAK is a community coffee token on the Stellar network. It is (1) a payment token coffee shops accept, (2) a digital coupon entitling the holder to the community discounted coffee, (3) a fair share recording exactly how much each member contributed and is entitled to, and (4) a unit of account for coffee where 1 TAK is anchored to 20 grams of roasted Arabica coffee (one cup worth). The word TAK means "single/one", as in "one coffee".',
  'Token facts: Stellar blockchain, SEP-41 Soroban smart-contract token, symbol TAK, 7 decimals, elastic supply (minted/burned 1:1 against 20 g of coffee), non-custodial (members hold their own keys), bean anchor 1 TAK = 20 g of roasted Arabica (medium-dark), and a 1% transaction fee that is governance-adjustable.',
  'Per-cup economics: by pooling purchases the community buys beans at bulk/wholesale prices instead of the retail price local cafés pay. This cuts the bean cost of one coffee by roughly 30%, and member discounts typically reach about 20-30% off each cup without the café losing money.',
  'The mint/burn loop: a customer buys TAK at the issue price (the current bulk cost of 20 g of coffee) and the payment buys 20 g of coffee into the community store, minting exactly 1 TAK. A coffee shop returns collected TAK to the store, receives 20 g of dry coffee, and the token is burned. Supply expands only when coffee is added and contracts only when coffee leaves, so the reserve always covers circulating supply.',
  'Why Stellar: fast and cheap payments (seconds, fractions of a cent), energy-efficient consensus, purpose-built for real assets via SEP-41, and non-custodial by design so members keep their own keys.',
  'Ecosystem: a non-custodial PWA wallet (hold XLM and TAK, pay, browse shops, order ahead, track history), coffee ordering with Web Push notifications, a one-time free claim of 3 TAK for new members, coffee-themed games and a weekly lottery, a read-only Telegram assistant (balance, shops, history), and the in-app AI agent (this assistant).',
  'Roadmap: Phase 1 Pilot in Farahan (working wallet, TAK on Stellar testnet, a few pilot shops, games and free-claim faucet); Phase 2 Region (more cafés, first pooled purchases, live member discounts); Phase 3 Import & scale (bulk import, central storage and distribution, new cities, on-chain governance); Phase 4 National network (any TAK holder enjoys cheap quality coffee anywhere).',
  'Governance principles: fairness (share proportional to contribution, recorded on a public ledger), self-custody, transparency (pooled purchases and distributions are auditable), and gradual decentralization of decisions over the coffee reserve, pricing, and expansion.',
  'Risk note: TAK is a utility token for buying coffee, not an investment product; its value may fluctuate and it carries market, commodity, regulatory, technology, adoption, and execution risks.',
].join('\n');
